module.exports = [{
    cid: 2,
    fee: [{
        cid: 2,
        fee: "10400",
        fid: 2,
        name: "Programme Fee",
        action: "selected",
        status: null,
        duration: "Per Semester",
    }, ],
    uid: 1,
    fees: "12000",
    name: "M.Sc. IT",
    action: "selected",
    status: "active",
    duration: "3 Years",
    priority: 100,
    prospect: [{
        cid: 2,
        pid: 2,
        action: "selected",
        status: null,
        sectors: "IT Services;Hospitality Services;Retail & Manufacturing;Entertainment & Media",
        designations: "Designers;Designers",
    }, ],
    objective: "To inculcate among students technical skills like other regular courses;To prepare students to design and conduct experiments, analyze and back up data.;To effectively analyze, design, and implement programming concepts.;To encourage a sense of professional and ethical responsibility among students.;To make students efficient for today’s IT emerging needs.",
    statelist: 29,
    courselist: 3,
    eligibility: "10+2 in any stream or equivalent",
    maxduration: "6 Years",
    minduration: "3 Years",
    eligibilitylist: 2,
    specializations: "Human Resource Management;Entrepreneurship and Leadership Management;Marketing & Sales Management;Production and Operations Management;Retail Management;Global Finance Market",
}, ];