module.exports = [{
        uid: 1,
        city: "dhanbad",
        name: "IGNOU",
        news: null,
        facts: "undefined",
        state: "Jharkhand",
        action: "selected",
        status: "inactive",
        street: "CH1/3 Moonidih",
        maxfees: "10000",
        minfees: null,
        pincode: "828129",
        ranking: null,
        priority: null,
        aiuapproved: 1,
        debapproved: 1,
        decapproved: 1,
        maxduration: "sabdgfb",
        minduration: null,
        ugcapproved: 1,
        aboutuniversity: "one of the finest collegesdfvfvrt",
        intcollaboration: null,
        typeofuniversity: "open university",
    },
    {
        uid: 2,
        city: "darbhaga",
        name: "raisys",
        news: null,
        facts: "undefined",
        state: "bihar",
        action: "selected",
        status: "darft",
        street: "laheria tower",
        maxfees: null,
        minfees: null,
        pincode: "893264",
        ranking: [{
            rid: 32,
            uId: 2,
            action: "selected",
            status: "active",
            ranking: "50",
            authority: "Outlook",
            rankingyear: "2020",
        }, ],
        priority: null,
        aiuapproved: 1,
        debapproved: 1,
        decapproved: 1,
        maxduration: null,
        minduration: null,
        ugcapproved: 0,
        aboutuniversity: "one of the best college in bihar",
        intcollaboration: null,
        typeofuniversity: "openuniversity",
    },
    {
        uid: 3,
        city: "darbhaga",
        name: "raisys",
        news: null,
        facts: "undefined",
        state: "bihar",
        action: "selected",
        status: "inactive",
        street: "laheria tower",
        maxfees: null,
        minfees: null,
        pincode: "893264",
        ranking: null,
        priority: null,
        aiuapproved: 0,
        debapproved: 0,
        decapproved: 0,
        maxduration: null,
        minduration: null,
        ugcapproved: 1,
        aboutuniversity: "one of the best college in bihar",
        intcollaboration: null,
        typeofuniversity: "openuniversity",
    },
    {
        uid: 4,
        city: "darbhaga",
        name: "raisys",
        news: null,
        facts: null,
        state: "bihar",
        action: "selected",
        status: "darft",
        street: "laheria tower",
        maxfees: null,
        minfees: null,
        pincode: "893264",
        ranking: [{
                rid: 2,
                uId: 4,
                action: "selected",
                status: null,
                ranking: "1",
                authority: "deb",
                rankingyear: "2020",
            },
            {
                rid: 3,
                uId: 4,
                action: "selected",
                status: null,
                ranking: "10",
                authority: "nirf",
                rankingyear: "2021",
            },
        ],
        priority: null,
        aiuapproved: 0,
        debapproved: 0,
        decapproved: 0,
        maxduration: null,
        minduration: null,
        ugcapproved: 0,
        aboutuniversity: "one of the best college in bihar",
        intcollaboration: null,
        typeofuniversity: "openuniversity",
    },
    {
        uid: 5,
        city: "darbhaga",
        name: "raisys",
        news: null,
        facts: "undefined",
        state: "bihar",
        action: "selected",
        status: "darft",
        street: "laheria tower",
        maxfees: null,
        minfees: null,
        pincode: "893264",
        ranking: [{
                rid: 4,
                uId: 5,
                action: "selected",
                status: null,
                ranking: "1ew",
                authority: "deb",
                rankingyear: "2020",
            },
            {
                rid: 5,
                uId: 5,
                action: "selected",
                status: null,
                ranking: "10",
                authority: "nirfede",
                rankingyear: "2021",
            },
        ],
        priority: null,
        aiuapproved: 1,
        debapproved: 0,
        decapproved: 1,
        maxduration: null,
        minduration: null,
        ugcapproved: 1,
        aboutuniversity: "one of the best college in bihar",
        intcollaboration: null,
        typeofuniversity: "openuniversity",
    },
    {
        uid: 6,
        city: "darbhaga",
        name: "raisys",
        news: null,
        facts: "undefined",
        state: "bihar",
        action: "selected",
        status: "darft",
        street: "lala chowk tower",
        maxfees: null,
        minfees: null,
        pincode: "893264",
        ranking: [{
                rid: 6,
                uId: 6,
                action: "selected",
                status: "inactive",
                ranking: "1w",
                authority: "NIRF",
                rankingyear: "2020",
            },
            {
                rid: 7,
                uId: 6,
                action: "selected",
                status: "inactive",
                ranking: "10",
                authority: "AIU",
                rankingyear: "2021",
            },
            {
                rid: 28,
                uId: 6,
                action: "selected",
                status: "active",
                ranking: "1",
                authority: "outlook",
                rankingyear: "2015",
            },
            {
                rid: 29,
                uId: 6,
                action: "selected",
                status: "active",
                ranking: "10",
                authority: "indiatodat",
                rankingyear: "2020",
            },
            {
                rid: 30,
                uId: 6,
                action: "selected",
                status: "active",
                ranking: "1",
                authority: "outlook",
                rankingyear: "2015",
            },
            {
                rid: 31,
                uId: 6,
                action: "selected",
                status: "active",
                ranking: "10",
                authority: "indiatodat",
                rankingyear: "2020",
            },
        ],
        priority: null,
        aiuapproved: 1,
        debapproved: 1,
        decapproved: 1,
        maxduration: null,
        minduration: null,
        ugcapproved: 1,
        aboutuniversity: "one of the best college in bihar whis was know from ancient time",
        intcollaboration: null,
        typeofuniversity: "openuniversity",
    },
    {
        uid: 7,
        city: "Patna",
        name: "Patna College",
        news: null,
        facts: "undefined",
        state: "bihar",
        action: "selected",
        status: "darft",
        street: "laheria tower",
        maxfees: null,
        minfees: null,
        pincode: "893264",
        ranking: [{
                rid: 8,
                uId: 7,
                action: "selected",
                status: null,
                ranking: "1sedsw3e",
                authority: "NIRF",
                rankingyear: "2022",
            },
            {
                rid: 9,
                uId: 7,
                action: "selected",
                status: null,
                ranking: "140s",
                authority: "AIU",
                rankingyear: "202sd1",
            },
        ],
        priority: null,
        aiuapproved: 0,
        debapproved: 1,
        decapproved: 1,
        maxduration: null,
        minduration: null,
        ugcapproved: 1,
        aboutuniversity: "one of the best college in bihar",
        intcollaboration: null,
        typeofuniversity: "openuniversity",
    },
    {
        uid: 8,
        city: "Patna",
        name: "Patna College",
        news: [{
                nid: 2,
                uId: 8,
                link: "url",
                title: "undefined",
                action: "selected",
            },
            {
                nid: 3,
                uId: 8,
                link: "url",
                title: "undefined",
                action: "selected",
            },
        ],
        facts: "undefined",
        state: "bihar",
        action: "selected",
        status: "darft",
        street: "laheria tower",
        maxfees: null,
        minfees: null,
        pincode: "893264",
        ranking: [{
                rid: 10,
                uId: 8,
                action: "selected",
                status: null,
                ranking: "1",
                authority: "NIRF",
                rankingyear: "2020",
            },
            {
                rid: 11,
                uId: 8,
                action: "selected",
                status: null,
                ranking: "10",
                authority: "AIU",
                rankingyear: "2021",
            },
        ],
        priority: null,
        aiuapproved: 0,
        debapproved: 0,
        decapproved: 0,
        maxduration: null,
        minduration: null,
        ugcapproved: 0,
        aboutuniversity: "one of the best college in bihar",
        intcollaboration: null,
        typeofuniversity: "openuniversity",
    },
    {
        uid: 9,
        city: "Patna",
        name: "Patna College",
        news: [{
                nid: 4,
                uId: 9,
                link: "url",
                title: "undefined",
                action: "selected",
            },
            {
                nid: 5,
                uId: 9,
                link: "url",
                title: "undefined",
                action: "selected",
            },
        ],
        facts: "undefined",
        state: "bihar",
        action: "selected",
        status: "darft",
        street: "laheria tower",
        maxfees: null,
        minfees: null,
        pincode: "893264",
        ranking: [{
                rid: 12,
                uId: 9,
                action: "selected",
                status: null,
                ranking: "1",
                authority: "NIRF",
                rankingyear: "2020",
            },
            {
                rid: 13,
                uId: 9,
                action: "selected",
                status: null,
                ranking: "10",
                authority: "AIU",
                rankingyear: "2021",
            },
        ],
        priority: null,
        aiuapproved: 0,
        debapproved: 0,
        decapproved: 0,
        maxduration: null,
        minduration: null,
        ugcapproved: 0,
        aboutuniversity: "one of the best college in bihar",
        intcollaboration: null,
        typeofuniversity: "openuniversity",
    },
    {
        uid: 10,
        city: "Patna",
        name: "Patna College",
        news: [{
                nid: 6,
                uId: 10,
                link: "url",
                title: "undefined",
                action: "selected",
            },
            {
                nid: 7,
                uId: 10,
                link: "url",
                title: "undefined",
                action: "selected",
            },
        ],
        facts: "undefined",
        state: "bihar",
        action: "selected",
        status: "darft",
        street: "laheria tower",
        maxfees: null,
        minfees: null,
        pincode: "893264",
        ranking: [{
                rid: 14,
                uId: 10,
                action: "selected",
                status: null,
                ranking: "1",
                authority: "NIRF",
                rankingyear: "2020",
            },
            {
                rid: 15,
                uId: 10,
                action: "selected",
                status: null,
                ranking: "10",
                authority: "AIU",
                rankingyear: "2021",
            },
        ],
        priority: null,
        aiuapproved: 0,
        debapproved: 0,
        decapproved: 0,
        maxduration: null,
        minduration: null,
        ugcapproved: 0,
        aboutuniversity: "one of the best college in bihar",
        intcollaboration: null,
        typeofuniversity: "openuniversity",
    },
    {
        uid: 11,
        city: "Patna",
        name: "Patna College",
        news: [{
                nid: 8,
                uId: 11,
                link: "url",
                title: "undefined",
                action: "selected",
            },
            {
                nid: 9,
                uId: 11,
                link: "url",
                title: "undefined",
                action: "selected",
            },
        ],
        facts: "undefined",
        state: "bihar",
        action: "selected",
        status: "darft",
        street: "laheria tower",
        maxfees: null,
        minfees: null,
        pincode: "893264",
        ranking: [{
                rid: 16,
                uId: 11,
                action: "selected",
                status: null,
                ranking: "1",
                authority: "NIRF",
                rankingyear: "2020",
            },
            {
                rid: 17,
                uId: 11,
                action: "selected",
                status: null,
                ranking: "10",
                authority: "AIU",
                rankingyear: "2021",
            },
            {
                rid: 18,
                uId: 11,
                action: "selected",
                status: null,
                ranking: "1",
                authority: "deb",
                rankingyear: "2020",
            },
            {
                rid: 19,
                uId: 11,
                action: "selected",
                status: null,
                ranking: "10",
                authority: "nirf",
                rankingyear: "2021",
            },
            {
                rid: 20,
                uId: 11,
                action: "selected",
                status: null,
                ranking: "1",
                authority: "deb",
                rankingyear: "2020",
            },
            {
                rid: 21,
                uId: 11,
                action: "selected",
                status: null,
                ranking: "10",
                authority: "nirf",
                rankingyear: "2021",
            },
            {
                rid: 22,
                uId: 11,
                action: "selected",
                status: null,
                ranking: "1",
                authority: "deb",
                rankingyear: "2020",
            },
            {
                rid: 23,
                uId: 11,
                action: "selected",
                status: "inactive",
                ranking: "10",
                authority: "nirf",
                rankingyear: "2021",
            },
        ],
        priority: null,
        aiuapproved: 0,
        debapproved: 0,
        decapproved: 0,
        maxduration: null,
        minduration: null,
        ugcapproved: 1,
        aboutuniversity: "one of the best college in bihar",
        intcollaboration: null,
        typeofuniversity: "openuniversity",
    },
    {
        uid: 22,
        city: "xasxas",
        name: "Nam of the colefe",
        news: null,
        facts: null,
        state: null,
        action: "selected",
        status: null,
        street: "xasxdas",
        maxfees: null,
        minfees: null,
        pincode: null,
        ranking: null,
        priority: null,
        aiuapproved: 1,
        debapproved: 0,
        decapproved: 0,
        maxduration: null,
        minduration: null,
        ugcapproved: 1,
        aboutuniversity: "scascdsa",
        intcollaboration: null,
        typeofuniversity: null,
    },
];